### ISSUE TITLE
Demo not working and Import Question

### ISSUE THREAD

**Issue by MikeiLL** [JoeWells/expanded-card#3]
Hey man. Looks like a nice package, but the demo is not working. I'm also a bit confused with all of the imports of `html` files. I have never seen that before.

**Comment by JoeWells** [comment]
Hey, not sure why the demos not working - seems to be working on my end. What browser are you using?

This project's based on Google's Polymer project which relies on importing different 'elements' through HTML imports (polymer-project.org).
This particular project/element was designed to compliment the preexisting 'paper-material' element (https://elements.polymer-project.org/elements/paper-material) by allowing it to expand and display more content with an icon and animation. However it now seems like Google has implemented this in to their own 'paper-card' element (https://elements.polymer-project.org/elements/paper-card) so if you wanted this functionality I'd recommend using theirs and not this.

I hope that makes sense?

**Comment by MikeiLL** [comment]
Thanks, man. I'm on the latest version of Firefox (46.0.1) and Google's demo of the expanding card does not work (does in Safari) so I'm going a different direction anyway.

**Comment by JoeWells** [comment]
Alright no problem!
